export enum HYPIXEL_ONE_TIME_ACHIEVEMENTS {
    "general_first_chat",
    "skywars_gotcha",
    "skywars_gapple",
    "general_first_party",
    "skywars_mob_spawner",
    "skywars_shiny_stuff",
    "general_youtuber",
    "skywars_touch_of_death",
    "truecombat_strategist",
    "truecombat_redstone_dealer",
    "truecombat_destiny_calls",
    "truecombat_dominating",
    "truecombat_cross_fingers",
    "truecombat_golden_bounty",
    "truecombat_wither_slayer",
    "truecombat_deadly_donation",
    "skywars_well_well",
    "skywars_fists_of_fury",
    "skywars_fast_and_furious",
    "general_use_portal",
    "blitz_first_game",
    "general_first_game",
    "skywars_now_im_enchanted",
    "skywars_fortunate",
    "skywars_gone_fishing",
    "supersmash_botmon_challenge",
    "supersmash_botmon_vs_spooderman",
    "supersmash_supremacy",
    "supersmash_domination",
    "supersmash_need_all",
    "supersmash_second_round",
    "supersmash_too_easy",
    "blitz_enchant_sword",
    "blitz_full_inventory",
    "blitz_kill_without_kit",
    "blitz_first_blood",
    "blitz_get_diamond_sword",
    "blitz_find_blitz",
    "blitz_apocalypse",
    "blitz_enchanted_armor",
    "blitz_youtuber",
    "blitz_fish_kill",
    "arena_totem_destroyer",
    "blitz_win_before_deathmatch",
    "general_first_friend",
    "blitz_craft_bread",
    "quake_bogof",
    "quake_good_guy_gamer",
    "quake_first_kill",
    "tntgames_tnt_run_purchase_potion",
    "tntgames_bow_spleef_first_win",
    "quake_perfection",
    "quake_simple_things",
    "quake_team_player",
    "skywars_legendary",
    "skywars_max_perk",
    "skywars_trolol",
    "blitz_level_seven",
    "skywars_nick_cage",
    "speeduhc_potion_brewer",
    "speeduhc_melon_smasher",
    "speeduhc_golden_apple",
    "speeduhc_rusher",
    "speeduhc_god_apple",
    "speeduhc_ride_pig",
    "uhc_shiny_rock",
    "uhc_adrenaline",
    "uhc_ride_a_horse",
    "uhc_crafting_revolution",
    "speeduhc_enchanted_armor",
    "arcade_pig_fishing_super_bacon",
    "uhc_enderkind",
    "quake_my_way",
    "quake_looking_fancy",
    "speeduhc_enchanted_book",
    "uhc_ghast",
    "uhc_music",
    "skywars_enderdragon",
    "arcade_mini_hunter",
    "paintball_unlock_hat",
    "paintball_no_killstreaks",
    "uhc_drink_with_caution",
    "uhc_no_problem_here",
    "tntgames_bow_spleef_first_double_jump",
    "arena_magical",
    "walls3_find_chest",
    "vampirez_purchase_blood",
    "vampirez_purchase_sword",
    "vampirez_vampire_shop",
    "vampirez_blood",
    "uhc_ultimate_crafting",
    "skywars_speed_runner",
    "general_friends_25",
    "uhc_prestigious",
    "arcade_bounty_hunter_target_killer",
    "general_vip",
    "general_vip_plus",
    "copsandcrims_fancy_new_toys",
    "copsandcrims_deathmatch_specialist",
    "copsandcrims_challenge_completed",
    "copsandcrims_like_my_gun",
    "copsandcrims_homing_bullets",
    "copsandcrims_samurai_warrior",
    "quake_buffing_up",
    "quake_what_have_i_done",
    "copsandcrims_run_away",
    "skywars_solo_warrior",
    "arcade_creeper_attack_iron_golem",
    "tntgames_tnt_run_first_win",
    "arcade_creeper_attack_survival",
    "skyclash_my_playstyle",
    "skyclash_powerspike",
    "skyclash_im_a_wizard",
    "skyclash_assassination",
    "skyclash_addicted",
    "skyclash_stay",
    "skyclash_skymon_go",
    "arcade_team_slayer",
    "blitz_spawn_horse",
    "uhc_bye_cruel_world",
    "uhc_ultimate_recipe",
    "vampirez_purchase_armor",
    "vampirez_kill_zombies",
    "vampirez_purchase_gold",
    "vampirez_purchase_food",
    "vampirez_gold",
    "vampirez_vampire_kills_one_round",
    "vampirez_sole_survivor",
    "walls3_first_skill_upgrade",
    "walls3_first_gathering_skill_upgrade",
    "walls3_attack_wither",
    "walls3_win_before_deathmatch",
    "walls3_win_with_living_wither",
    "walls3_advanced_strategies",
    "walls_first_perk",
    "walls_first_kit",
    "arcade_farm_hunt_disguise",
    "skywars_lucky_souls",
    "skywars_open_chest",
    "skywars_peacemaker",
    "skywars_siege",
    "skywars_speed_run",
    "skywars_who_needs_teammates",
    "warlords_chain_kill",
    "warlords_i_have_to_concentrate",
    "warlords_first_of_many",
    "warlords_medium_rare",
    "skywars_baller",
    "paintball_unlock_killstreaks",
    "skyclash_trained_well",
    "quake_billy_talent",
    "supersmash_skullfire_challenge",
    "paintball_combo",
    "truecombat_legendary",
    "truecombat_not_today",
    "skywars_well_deserved",
    "warlords_eagle_eyed",
    "warlords_juiced_up",
    "warlords_makin_some_room",
    "paintball_first_kill",
    "paintball_last_kill",
    "supersmash_frostmage_challenge",
    "copsandcrims_warfare_stylist",
    "walls3_mine_diamond",
    "uhc_kit_mastery",
    "supersmash_karakot_challenge",
    "arcade_world_economics",
    "blitz_seven_kits",
    "speeduhc_mastery_unlock",
    "copsandcrims_gun_master",
    "copsandcrims_grafitti_king",
    "copsandcrims_flawless",
    "copsandcrims_hunting_season",
    "copsandcrims_triipplee",
    "tntgames_tnt_run_no_sprinting",
    "warlords_that_was_easy",
    "truecombat_ender_dragon",
    "copsandcrims_on_fire",
    "warlords_legendary",
    "truecombat_diamond_armor",
    "warlords_avengers_wrath",
    "warlords_purple_power",
    "skywars_portal_game",
    "truecombat_lightning_fast",
    "general_gifting",
    "copsandcrims_one_shot_one_kil",
    "tntgames_wizards_first_win",
    "skywars_hasta_la_vista",
    "tntgames_bow_spleef_double_jump_upgrade",
    "blitz_use_wolf_tamer",
    "skyclash_missing_apple",
    "skyclash_rusher",
    "skyclash_rest_in_pepperoni",
    "skyclash_no_alchemy",
    "skyclash_boo",
    "copsandcrims_comeback_story",
    "quake_humiliation",
    "quake_not_working",
    "quake_redstoner",
    "copsandcrims_darude_sandstorm",
    "gingerbread_getting_good",
    "gingerbread_get_hit_by_me",
    "gingerbread_new_style",
    "gingerbread_taste_my_banana",
    "tntgames_bow_spleef_triple_shot_upgrade",
    "copsandcrims_sneaky",
    "arena_offensive",
    "arena_utility",
    "arena_support",
    "arena_ultimate",
    "arena_runic",
    "copsandcrims_team_communicator",
    "copsandcrims_street_artist",
    "quake_fly",
    "quake_frog",
    "quake_doubling_up",
    "copsandcrims_too_easy",
    "skywars_kill_streak",
    "vampirez_undefeatable",
    "copsandcrims_umadbro",
    "copsandcrims_unstoppable",
    "vampirez_close_call",
    "walls_vampirism",
    "supersmash_two_for_one",
    "copsandcrims_pentaaaa",
    "tntgames_bow_spleef_repulsor_upgrade",
    "copsandcrims_the_carrier",
    "copsandcrims_never_too_late",
    "tntgames_tnt_parkour",
    "tntgames_tnt_tag_differenttags",
    "tntgames_tnt_tag_tagger",
    "tntgames_wizards_jumper",
    "tntgames_wizards_leaderboard",
    "tntgames_wizards_hurts",
    "tntgames_wizards_lead",
    "tntgames_spleef_repulsor",
    "tntgames_tnt_tag_first_win",
    "tntgames_tnt_tag_dm",
    "tntgames_tnt_tag_close",
    "supersmash_the_peak",
    "supersmash_reach_sky",
    "tntgames_spleef_exhausted",
    "tntgames_spleef_shots",
    "tntgames_spleef_hits",
    "tntgames_wizards_nogood",
    "tntgames_pvp_run_first_win",
    "tntgames_tnt_tag_snowball",
    "tntgames_tnt_tag_traveller",
    "tntgames_tnt_tag_blownup",
    "skyclash_bad_karma",
    "tntgames_tnt_tag_dangerous",
    "tntgames_pvp_run_sabotage",
    "tntgames_wizards_caphelp",
    "copsandcrims_wheres_my_nuke",
    "copsandcrims_late_to_the_party",
    "tntgames_spleef_triple",
    "tntgames_pvp_run_flying",
    "tntgames_tnt_run_short",
    "arena_pairs",
    "truecombat_gold_digger",
    "tntgames_spleef_noperks",
    "paintball_activate_killstreaks",
    "quake_show_me_the_money",
    "quake_presidential",
    "quake_heart_stopper",
    "copsandcrims_close_call",
    "quake_one_shot",
    "tntgames_tnt_run_nodjs",
    "quake_perfectionnist",
    "tntgames_run_potions",
    "tntgames_pvp_run_potions",
    "tntgames_pvp_run_halfhearted",
    "tntgames_pvp_run_triple",
    "quake_fanatic",
    "skyclash_dream_team",
    "skyclash_flying",
    "tntgames_tnt_run_flying",
    "skywars_sniper",
    "tntgames_wizards_fire_wizard_explode",
    "tntgames_wizards_thirty_kills",
    "tntgames_wizards_triple",
    "tntgames_tnt_npcs",
    "quake_want_a_wardrobe",
    "arcade_untouchable",
    "walls_craft_flint",
    "walls_craft_boat",
    "walls_revenge",
    "copsandcrims_grenade_kill",
    "skywars_lucky_charm",
    "walls_berserk",
    "arcade_savage",
    "arena_health",
    "tntgames_tnt_wins_in_a_row",
    "quake_in_my_way",
    "paintball_activate_plus_ten",
    "paintball_activate_leeroy_jenkins",
    "skywars_no_chest_challenge",
    "quake_untouchable",
    "quake_baking_a_dozen",
    "quake_incredible",
    "walls_starter_kits",
    "gingerbread_im_lucky",
    "gingerbread_coins_please",
    "speeduhc_kit_unlock",
    "supersmash_experience_express",
    "speeduhc_paper_cut",
    "warlords_feeling_special",
    "warlords_this_better_be_good",
    "tntgames_spleef_noshots",
    "speeduhc_kill_ghast",
    "blitz_pigrider",
    "walls_canadian_kit",
    "vampirez_chest_hunter",
    "arcade_creeper_attack_waves",
    "arena_melee",
    "vampirez_zombie_slayer",
    "skyclash_lightweight",
    "skyclash_are_you_crazy",
    "tntgames_tnt_run_firstlayer",
    "tntgames_tnt_run_effects",
    "blitz_finally",
    "blitz_cooking_expert",
    "blitz_not_skywars",
    "blitz_rambo",
    "blitz_champion",
    "blitz_coin_festival",
    "blitz_no_problem",
    "quake_apple_corer",
    "bedwars_first",
    "bedwars_first_blood",
    "bedwars_team_player",
    "bedwars_already_over",
    "bedwars_destroy_beds",
    "bedwars_super_looter",
    "bedwars_strategist",
    "bedwars_builder",
    "bedwars_merciless",
    "skyclash_new_passive",
    "bedwars_ultimate_defense",
    "bedwars_geared_up",
    "bedwars_survivor",
    "bedwars_alchemist",
    "bedwars_emerald_hoarder",
    "bedwars_bed_trap",
    "bedwars_fireballs",
    "blitz_rampage",
    "bedwars_diamond_hoarder",
    "bedwars_iron_punch",
    "bedwars_dont_need_bed",
    "bedwars_shear_luck",
    "bedwars_golem",
    "bedwars_pickaxe_challenge",
    "bedwars_sniper",
    "arcade_no_mercy",
    "arcade_throw_out_powerup_kill",
    "blitz_blitz_maniac",
    "arcade_over_here",
    "arcade_woops_didnt_mean_to",
    "arcade_ptb_ride_bat",
    "arcade_overpowered",
    "arcade_giddy_up_horsey",
    "bedwars_slayer",
    "blitz_under_the_sea",
    "blitz_bomberman",
    "blitz_no_regrets",
    "arena_pool",
    "walls_catch_fish",
    "gingerbread_never_lucky",
    "gingerbread_tryharder",
    "supersmash_tinman_challenge",
    "arcade_dragon_killer",
    "arcade_trampolinio_red_wool",
    "tntgames_pvp_run_manykills",
    "walls_engineer",
    "paintball_admin_hat",
    "tntgames_pvp_run_nohit",
    "blitz_unfortunate",
    "blitz_no_looting",
    "tntgames_pvp_run_fists",
    "tntgames_pvp_run_pacifist",
    "speeduhc_kit_specialist",
    "speeduhc_domination",
    "speeduhc_kill_tnt",
    "tntgames_pvp_run_nodjs",
    "quake_oh_baby_a_triple",
    "quake_how_did_that_happen",
    "skyclash_kawaii_pants",
    "blitz_unstoppable",
    "skyclash_uhc_challenge",
    "skyclash_whats_next",
    "skyclash_happy_little_achievement",
    "skyclash_greatman",
    "blitz_afterburner",
    "arcade_hoehoehoe_score",
    "arcade_avalance_waves",
    "arcade_party_games_stars",
    "arcade_rpg_16_rocket_pig",
    "arcade_professional_mower",
    "arena_punisher",
    "speeduhc_use_enderpearl",
    "speeduhc_snipe_player",
    "arcade_animal_slaughter",
    "skyclash_sharp_justice",
    "tntgames_wizards_heal",
    "vampirez_potions",
    "vampirez_wizard",
    "skyclash_void_killer",
    "blitz_titanium",
    "uhc_seafood",
    "walls3_birds_eye",
    "tntgames_wizards_blood_wizard_regen",
    "quake_dark_side",
    "skyclash_max_power",
    "blitz_rabbits_foot",
    "blitz_lucky_minions",
    "quake_going_up_in_life",
    "skyclash_kill_secured",
    "arcade_dragon_slayer",
    "quake_diamonds_to_you",
    "quake_one_in_the_chamber",
    "paintball_hacker",
    "housing_give_cookie",
    "quake_love_is_in_the_air",
    "quake_my_precious",
    "skyclash_endless_quiver",
    "murdermystery_be_the_hero",
    "murdermystery_win_while_invincible",
    "murdermystery_three_knife_throw_kills",
    "murdermystery_sword_kill_long_range",
    "murdermystery_play_both_games",
    "murdermystery_play_game_in_lobby",
    "murdermystery_hit_by_sword_while_invinc",
    "murdermystery_blessing_and_curse",
    "murdermystery_thirty_gold_picked_up",
    "murdermystery_soldiers_eliminated",
    "murdermystery_three_arrows",
    "murdermystery_clear_cacti",
    "murdermystery_ride_monorail",
    "murdermystery_secret_chamber",
    "murdermystery_kill_murderer_after_kill",
    "murdermystery_all_directions",
    "murdermystery_pickup_gold",
    "murdermystery_win_inno_monorail",
    "murdermystery_win_survivor_due_to_time",
    "murdermystery_survive_storm_on_top",
    "murdermystery_five_curses",
    "murdermystery_kali_favor",
    "murdermystery_shoot_thrown_knife",
    "murdermystery_kill_on_horse",
    "murdermystery_return_from_dead_win",
    "murdermystery_first_shot_hit",
    "murdermystery_special_two_in_a_row",
    "murdermystery_block_with_barrier",
    "general_a_long_journey_begins",
    "murdermystery_bow_killstreak",
    "murdermystery_murderer_bow_kills",
    "murdermystery_bow_kill_on_detective",
    "murdermystery_kill_in_rapid_transport",
    "murdermystery_kill_murderer_as_last_alive",
    "arena_flawless",
    "skywars_fear_me",
    "murdermystery_win_as_murderer_short_time",
    "murdermystery_kill_detective_fast",
    "halloween2017_good_try",
    "halloween2017_hi_there",
    "halloween2017_second_ghost",
    "halloween2017_tbr_observatory_spin",
    "halloween2017_all_ghosts",
    "halloween2017_spooky_chest",
    "murdermystery_win_murderer_fell_in_trap",
    "halloween2017_pumpkin_dancer",
    "halloween2017_pumpkin_death",
    "halloween2017_tbr_observatory_spin_1_10",
    "murdermystery_murderer_first_kill",
    "tntgames_tnt_tag_aww",
    "blitz_invincible",
    "skyclash_im_a_better_wizard",
    "supersmash_void_challenge",
    "arena_spartacus",
    "general_achievement_npc",
    "skyclash_archer_challenge",
    "truecombat_rushmode",
    "supersmash_cake_challenge",
    "quake_its_so_shiny",
    "uhc_puppy",
    "uhc_eldorado",
    "christmas2017_hunt_begins",
    "christmas2017_legendary",
    "christmas2017_merry_christmas",
    "christmas2017_real_santa",
    "christmas2017_eat_this",
    "christmas2017_uh_uh",
    "christmas2017_not_my_mom",
    "christmas2017_sugar_rush",
    "christmas2017_bouncy_castle",
    "christmas2017_christmas_quest",
    "christmas2017_nom_nom",
    "christmas2017_sharing_is_caring",
    "christmas2017_santa_helper",
    "christmas2017_dem_cows",
    "christmas2017_greed_incarnate",
    "christmas2017_steal_fairly",
    "christmas2017_respect_your_elder",
    "christmas2017_blacksmith",
    "tntgames_tnt_run_nomove",
    "tntgames_wizards_assistant",
    "copsandcrims_is_it_good_now",
    "vampirez_dont_need_it",
    "murdermystery_kill_murderer_while_blinded",
    "warlords_are_you_kidding_me",
    "warlords_giddy_up",
    "skyclash_golden_one",
    "tntgames_wizards_awizard",
    "arcade_gotta_catch_them_all",
    "walls3_save_your_stuff",
    "murdermystery_no_gold_pickup",
    "murdermystery_drink_many_potions",
    "murdermystery_kill_while_monorail",
    "quake_calm_down",
    "walls3_seasons_greetings",
    "walls_get_diamond_sword",
    "walls_create_portal",
    "truecombat_knight",
    "truecombat_sharpened_katana",
    "supersmash_gencluck_challenge",
    "supersmash_spooderman_challenge",
    "supersmash_pug_challenge",
    "supersmash_get_over_here",
    "supersmash_marauder_challenge",
    "supersmash_bulk_challenge",
    "supersmash_teamwork",
    "truecombat_chance",
    "truecombat_rampage",
    "truecombat_doctor",
    "truecombat_boom",
    "truecombat_what_have_i_done",
    "truecombat_this_is_too_easy",
    "copsandcrims_friendly_game",
    "copsandcrims_secret_order",
    "truecombat_invincible",
    "truecombat_gone_peaceful",
    "skyclash_skyclash_expert",
    "buildbattle_over_99",
    "buildbattle_teamwork",
    "buildbattle_legendary",
    "buildbattle_ooo_shiny",
    "buildbattle_every_second_counts",
    "buildbattle_no_mistakes",
    "buildbattle_braniac",
    "buildbattle_artist",
    "buildbattle_mobster",
    "buildbattle_obvious",
    "buildbattle_fancy",
    "buildbattle_guessing_streak",
    "buildbattle_superior_vote",
    "buildbattle_stenographer",
    "buildbattle_professional_builder",
    "buildbattle_fast_typer",
    "buildbattle_intuition",
    "buildbattle_that_wood_be_perfect",
    "buildbattle_pro_winner",
    "murdermystery_longrange_shot",
    "buildbattle_musician",
    "murdermystery_killstreak",
    "quake_grab_it_all",
    "uhc_total_domination",
    "arcade_cant_hide_from_me",
    "skyclash_no_chest",
    "walls3_i_feel_sick",
    "truecombat_sticky_situation",
    "truecombat_toxic",
    "buildbattle_perfect_harmony",
    "supersmash_shoop_challenge",
    "walls3_veteran",
    "murdermystery_last_survivor",
    "murdermystery_top_zombie",
    "walls3_max_zombie_skills",
    "walls3_max_skills",
    "walls3_gone_vegan",
    "truecombat_maxed_perk",
    "truecombat_gold_forager",
    "gingerbread_gettin_paid",
    "walls3_peacekreeper",
    "arcade_creeper_attack_upgrades",
    "uhc_bomberman",
    "skyclash_half_health_challenge",
    "skyclash_anvil_kill",
    "blitz_find_head",
    "duels_my_preference",
    "duels_not_close_at_all",
    "duels_competitor",
    "duels_replay",
    "duels_the_waiting_game",
    "duels_speed_duel",
    "duels_burn_baby_burn",
    "duels_fortification",
    "duels_not_hungary",
    "duels_team_player",
    "duels_axe_you_a_question",
    "duels_well_rounded",
    "duels_we_are_number_one",
    "duels_smash_your_keyboard",
    "duels_trial_by_combat",
    "duels_rematch",
    "duels_more_damage",
    "walls3_this_is_my_final_form",
    "skyclash_ultimate_warrior_challenge",
    "skyclash_bomber_challenge",
    "skyclash_god_of_monsters",
    "duels_summoner",
    "duels_domination",
    "duels_revenge",
    "buildbattle_classic_man",
    "arena_energy",
    "quake_bubbly",
    "quake_lookin_good",
    "arena_not_today",
    "arena_smash",
    "arena_overkill",
    "walls3_hard_as_steel",
    "walls3_whats_the_big_idea",
    "walls3_moodsetter",
    "speeduhc_skeleton_bow",
    "walls3_at_least_he_tried",
    "warlords_surprise_attack",
    "walls3_feels_bad",
    "walls3_max_herobrine_skills",
    "walls3_max_skeleton_skills",
    "walls3_exchange",
    "walls3_ready_set_boom",
    "walls3_max_render_distance",
    "walls3_happy",
    "walls3_bull_shark",
    "walls3_hammer_down",
    "walls3_whirlwind",
    "vampirez_survivor_kills_one_round",
    "vampirez_zombie_whisperer",
    "vampirez_first_wave_kill",
    "vampirez_vampire_fang_kill",
    "arena_cooldown",
    "quake_wat",
    "arcade_dragontamer",
    "gingerbread_is_this_survival_games",
    "walls3_to_infinity",
    "arcade_no_mutiny_today",
    "arcade_shooting_range_explosive_arrow",
    "arcade_lone_survivor",
    "vampirez_last_chance",
    "warlords_coming_through",
    "warlords_green_is_love",
    "warlords_i_got_you_bro",
    "warlords_i_must_resist",
    "walls_no_team_deaths",
    "walls_kill_cliff",
    "walls3_thanks_connor",
    "truecombat_explosive_archer",
    "truecombat_monster_hunter",
    "truecombat_dragon_slayer",
    "blitz_collector",
    "blitz_nickname",
    "blitz_preference",
    "blitz_too_basic",
    "blitz_sail_away",
    "blitz_experimentation",
    "blitz_max_blitz",
    "uhc_robin_hood",
    "housing_recieve_cookie",
    "walls3_i_am_cow",
    "walls_ride_horse",
    "housing_become_resident",
    "housing_make_resident",
    "housing_grand_opening",
    "housing_new_look",
    "walls3_born_talented",
    "walls3_speedy_mineman",
    "walls3_fire_in_the_hole",
    "arena_pig",
    "skywars_slow_steady",
    "skywars_rng",
    "skywars_map_select",
    "skywars_max_well",
    "skywars_criminal",
    "skywars_mystery_mob",
    "bridge_one_v_one_me",
    "skyclash_heroic_charge",
    "bridge_express_yourself",
    "bridge_hat_trick",
    "bridge_on_fire",
    "bridge_got_ya",
    "bridge_community_oriented",
    "bridge_ninja",
    "bridge_void_archer",
    "bridge_jumping_to_conclusions",
    "bridge_gg",
    "arcade_hide_and_seek_prop",
    "arcade_hide_and_seek_prop_hunter",
    "arcade_zombies_feels_good",
    "arcade_zombies_ultimate",
    "arcade_zombies_team_player",
    "arcade_zombies_electrician",
    "arcade_zombies_speed_runner",
    "arcade_zombies_win",
    "arcade_hide_and_seek_party_pooper",
    "arcade_zombies_perk_hoarder",
    "bridge_clean_sweep",
    "bedwars_savvy_shopper",
    "bedwars_its_dark_down_there",
    "bedwars_rejoining_the_dream",
    "bedwars_you_cant_do_that",
    "bedwars_mission_control",
    "bedwars_buggy_beds",
    "bedwars_bomber",
    "bedwars_minefield",
    "bedwars_ninja",
    "bedwars_sneaky_rusher",
    "bedwars_revenge",
    "bedwars_thats_a_first",
    "bedwars_stay_away_from_me",
    "bedwars_katniss_everdeen_style",
    "bedwars_distraction",
    "bedwars_out_of_stock",
    "bedwars_cutting_it_close",
    "bedwars_the_last_of_us",
    "skywars_playing_it_safe",
    "skywars_attention_seeking",
    "uhc_wealthy_champion",
    "walls3_esc",
    "walls3_inventory_management",
    "walls3_skitterama",
    "skywars_mega_warrior",
    "skywars_teamwork",
    "housing_join_guild",
    "housing_join_friend",
    "housing_join_staff",
    "housing_join_youtube",
    "walls3_blowing_bubbles",
    "walls3_morra",
    "walls3_much_dogs",
    "bedwars_getting_the_job_done_better",
    "walls3_avalanche",
    "walls3_chill_sniper",
    "copsandcrims_sniper",
    "copsandcrims_blind_kill",
    "copsandcrims_oh_baby_a_triple",
    "copsandcrims_quad_flash",
    "walls3_emp",
    "walls3_hug_me",
    "copsandcrims_sneak_kill",
    "copsandcrims_kamikaze",
    "housing_join_random",
    "tntgames_tnt_prestige",
    "blitz_so_shiny",
    "warlords_nifty",
    "walls3_thunder",
    "warlords_slow_down_there",
    "walls3_ashes_to_bashes",
    "walls3_cruising_flames",
    "warlords_collateral_damage",
    "walls3_time_to_diet",
    "walls3_time_to_feast",
    "walls3_legendary_werewolf",
    "walls3_speed_run",
    "warlords_lifeleech",
    "walls3_laser_precision",
    "buildbattle_the_hat_master",
    "walls3_geronimo",
    "walls3_taking_the_heat",
    "walls3_its_all_ogre_now",
    "walls3_failed_experiment",
    "walls3_high_on_ores",
    "walls3_stayin_alive",
    "walls3_ninja_7s",
    "walls3_competitive",
    "walls3_blood_lust",
    "walls3_throwing_coconuts",
    "walls3_revenge_of_the_wolves",
    "uhc_rampage",
    "walls3_whirlpool",
    "walls3_bow_down",
    "walls3_masterpiece",
    "walls3_untouchable",
    "murdermystery_dance",
    "murdermystery_jaws",
    "murdermystery_paranoid",
    "murdermystery_watson",
    "murdermystery_reichenbach_fall",
    "murdermystery_trigger_happy_havoc",
    "murdermystery_uncalculated",
    "murdermystery_emp",
    "murdermystery_stealth",
    "walls3_hunting_season",
    "walls3_into_the_future",
    "tntgames_overpowered_archery",
    "tntgames_spooky",
    "tntgames_dont_get_close",
    "tntgames_that_was_close",
    "tntgames_second_chance",
    "duels_gone_fishing",
    "duels_build_battle",
    "duels_untouchable",
    "duels_lobby_slayer",
    "duels_hawk_eye",
    "duels_speedy_sumo",
    "duels_close_call",
    "duels_getting_loot",
    "duels_ace",
    "duels_hungry",
    "duels_shut_down",
    "tntgames_bye_bye",
    "tntgames_kangaroo",
    "tntgames_grand_master",
    "tntgames_jack_of_all",
    "warlords_capture_the_win",
    "walls3_team_player",
    "warlords_beep_beep",
    "warlords_super_soaker",
    "warlords_power_up",
    "warlords_my_pleasure",
    "warlords_boot_camp",
    "warlords_bearing_gifts",
    "warlords_hammer_of_destruction",
    "warlords_world_travel",
    "warlords_super_powers",
    "warlords_right_on_time",
    "vampirez_upgraded",
    "vampirez_tastes_funny",
    "vampirez_nightmare",
    "vampirez_word_puns",
    "vampirez_blood_thirsty",
    "warlords_on_top",
    "warlords_total_domination",
    "vampirez_pest",
    "vampirez_purified",
    "warlords_solo_carry",
    "arena_not_even_close",
    "warlords_extensive_training",
    "quake_think_fast",
    "quake_squish",
    "quake_i_liek_turtles",
    "quake_double_trouble",
    "quake_death_chant",
    "quake_not_today",
    "quake_heavy_shoulders",
    "quake_fabulous_win",
    "quake_minigun",
    "quake_beyond_incredible",
    "walls3_timber",
    "quake_what_just_happened",
    "quake_tubular",
    "halloween2017_my_halloween_costume",
    "halloween2017_gravedigger",
    "halloween2017_fire_from_hell",
    "halloween2017_second_ghost_2018",
    "halloween2017_undead_target_practice",
    "halloween2017_rising_dead",
    "halloween2017_necrotherapy",
    "halloween2017_vampires_be_gone",
    "halloween2017_full_moon",
    "halloween2017_all_ghosts_2018",
    "halloween2017_classy_wither",
    "halloween2017_survivors_be_gone",
    "halloween2017_that_was_easy",
    "halloween2017_not_so_scary",
    "halloween2017_pumpkin_vision",
    "halloween2017_tbr_sharknado_jaunt",
    "halloween2017_blame_your_team",
    "halloween2017_the_crawling_dead",
    "halloween2017_tbr_midtown_trip",
    "halloween2017_corpse_still_runs",
    "halloween2017_tbr_kraken_assault",
    "halloween2017_tbr_midtown_trip_1_20",
    "halloween2017_tbr_sharknado_jaunt_fast",
    "halloween2017_tbr_kraken_assault_1_25",
    "halloween2017_el_spooder",
    "speeduhc_natural_talent",
    "halloween2017_october_betrayal",
    "quake_thanks_grandma",
    "vampirez_robbed",
    "walls3_mass_destruction",
    "gingerbread_honking_amazing",
    "gingerbread_modular",
    "gingerbread_eternally_awesome",
    "gingerbread_ungrateful",
    "gingerbread_mechanic",
    "gingerbread_boost_of_confidence",
    "gingerbread_cant_see_anything",
    "gingerbread_honking_mad",
    "gingerbread_javelins_rocket",
    "gingerbread_surface_to_air_missile",
    "gingerbread_well_versed",
    "gingerbread_lapped",
    "gingerbread_eat_my_dust",
    "gingerbread_missile_mayhem",
    "gingerbread_show_off",
    "gingerbread_sleeper_agent",
    "gingerbread_seen_it_all",
    "gingerbread_victors_prize",
    "gingerbread_nope",
    "gingerbread_shut_down",
    "gingerbread_flower_power",
    "gingerbread_chill_out",
    "gingerbread_coin_magnet",
    "gingerbread_front_man",
    "duels_one_v_one_me",
    "duels_express_yourself",
    "duels_community_oriented",
    "duels_hat_trick",
    "duels_ninja",
    "duels_on_fire",
    "duels_got_ya",
    "duels_heart_hoarder",
    "duels_clean_sweep",
    "duels_void_archer",
    "duels_last_stand",
    "duels_gg",
    "duels_carried",
    "paintball_how_does_it_feel",
    "paintball_now_you_see_me",
    "paintball_cheating_death",
    "paintball_espionage",
    "paintball_trigger_happy",
    "paintball_undercover_sloth",
    "paintball_energy_drink",
    "paintball_on_the_brink_of_defeat",
    "paintball_go_home_youre_drunk",
    "paintball_god_killer",
    "paintball_thunder_struck",
    "paintball_explosive_death",
    "paintball_sarcrifice",
    "paintball_sampling",
    "paintball_at_least_i_tried",
    "gingerbread_slippery",
    "paintball_lights_out",
    "gingerbread_contender",
    "gingerbread_seasonal_racer",
    "paintball_warfare_time",
    "paintball_shaky_hands",
    "walls3_not_a_golem",
    "paintball_closure",
    "truecombat_i_fna",
    "arena_new_toy",
    "arena_max_runic_magic",
    "arena_environmentalist",
    "arena_health_totem",
    "arena_nice_spare",
    "arena_spirited_away",
    "arena_you_shall_not_pass",
    "arena_dragon_within",
    "arena_power_hungry",
    "arena_my_new_hat",
    "arena_dont_touch_me",
    "arena_doom_shroom_gloom",
    "arena_big_brawler",
    "paintball_do_i_get_my_nuke_now",
    "paintball_jackson_pollock",
    "walls3_skeletons_best_friend",
    "walls3_circle_of_trust",
    "walls3_great_white",
    "walls3_lucky_sunny",
    "walls3_louis",
    "walls3_treasure_hunter",
    "walls3_breadlord",
    "walls_sole_survivor",
    "walls3_frosty_friendship",
    "walls3_collector",
    "walls3_coming_through",
    "walls3_constructor",
    "walls3_maximum_effort",
    "walls3_moo_brawl",
    "arena_iron_heart",
    "arena_hard_earned_reward",
    "walls3_grave_robber",
    "christmas2017_hunt_begins_2018",
    "christmas2017_real_santa_2018",
    "christmas2017_big_bag_o_gifts",
    "christmas2017_holidays_ruined",
    "christmas2017_holiday_miracle",
    "walls3_death_from_above",
    "warlords_warlord",
    "warlords_mad_skillz_yo",
    "supersmash_reach_stars",
    "walls3_rushlord",
    "christmas2017_let_it_snow",
    "christmas2017_snow_wars",
    "christmas2017_festivities",
    "christmas2017_close_enough",
    "christmas2017_empty_house",
    "christmas2017_christmas_is_saved",
    "christmas2017_swegmas",
    "christmas2017_winter_runner",
    "christmas2017_melting_killer",
    "christmas2017_christmas_topper",
    "christmas2017_do_you_wanna_build_a_snowman",
    "walls3_legendary_zombie",
    "walls3_sleepytime",
    "walls3_alchemy_100",
    "walls3_on_point",
    "walls3_legendary_arcanist",
    "walls3_potions_of_death",
    "walls3_marksman",
    "walls_customized",
    "walls_robin_hood",
    "walls_finding_nemo",
    "walls_not_today",
    "walls_burning",
    "walls_true_power",
    "walls_not_a_fish",
    "walls_record_label",
    "skywars_donator",
    "skywars_challenge_no_chest",
    "skywars_challenge_half_health",
    "skywars_challenge_uhc",
    "skywars_challenge_pro",
    "skywars_challenge_master",
    "skywars_challenge_rookie",
    "skywars_challenge_paper",
    "skywars_challenge_no_block",
    "skywars_challenge_ultimate_warrior",
    "skywars_challenge_archer",
    "skywars_happy_meal",
    "skywars_corruption_lord",
    "skywars_mythical",
    "truecombat_not_uhc",
    "copsandcrims_character_upgrades",
    "uhc_chest_of_fate",
    "uhc_dice_of_god",
    "paintball_endurance",
    "walls3_legendary_shark",
    "walls3_ba_boom",
    "walls3_legendary_squid",
    "walls3_legendary_phoenix",
    "walls3_legendary_hunter",
    "walls3_legendary_blaze",
    "walls3_blaze_party",
    "general_creeperbook",
    "walls3_legendary_skeleton",
    "walls3_legendary_enderman",
    "walls3_legendary_shaman",
    "walls3_legendary_dreadlord",
    "walls3_legendary_renegade",
    "walls3_legendary_spider",
    "walls3_legendary_pigman",
    "walls3_alotv1",
    "walls_wiped_out",
    "arena_deadly_pumpkin",
    "supersmash_young_apprentice",
    "walls3_captain_combo",
    "uhc_parkour_master",
    "uhc_warming_up",
    "uhc_dong",
    "uhc_elite_prestige",
    "uhc_crazy_hardcore",
    "uhc_deux_ex_machina",
    "uhc_powerhouse",
    "blitz_ultimate_combatant",
    "blitz_safety_first",
    "blitz_final_destination",
    "blitz_chaotic_madness",
    "blitz_close_call",
    "blitz_even_shinier",
    "walls3_gotcha",
    "walls3_dont_blink",
    "blitz_ultimate_completist",
    "blitz_donkeytamer_master",
    "paintball_godfather",
    "uhc_calling_upon_thor",
    "walls_untouchable",
    "walls3_wunderbar",
    "walls3_surprise",
    "blitz_ultimate_prestiger",
    "uhc_axe_of_perun",
    "walls3_you_shall_not_pass",
    "walls_ten_kills",
    "easter_first_egg_2019",
    "easter_blitz_spawn_rabbit",
    "easter_all_eggs_2019",
    "easter_towerwars_chickens",
    "easter_sw_egg_void",
    "easter_cvc_grenades",
    "easter_paintball_leeroy",
    "easter_uhc_golden_carrot",
    "easter_smash_cluck_kills",
    "easter_megawalls_jockey",
    "easter_arcade_chicken_race",
    "easter_mm_carrot_kills",
    "easter_bw_jump_boost",
    "easter_vampirez_carrot",
    "walls3_hammer_head",
    "truecombat_multikill",
    "walls3_legendary_golem",
    "walls3_legendary_snowman",
    "easter_pit_dragon_egg",
    "easter_easter_egg",
    "walls3_school_cancelled",
    "easter_happy_easter_2019",
    "walls3_legendary_automaton",
    "walls3_legendary_moleman",
    "warlords_undead_army",
    "arcade_hole_finals",
    "arcade_hypixel_says_master",
    "arcade_zombies_survivor",
    "arcade_zombes_serial_killer",
    "arcade_farm_hunt_killer",
    "arcade_dragon_wars_blast",
    "arcade_pixel_painters_one",
    "arcade_zombies_herobrine",
    "arcade_zombies_time_trial_blood",
    "arcade_football_speed",
    "arcade_football_five_goals",
    "arcade_mini_walls_last_man",
    "arcade_zombies_time_trial_dead",
    "arcade_hole_score",
    "arcade_mini_walls_damage",
    "warlords_shards_for_glory",
    "warlords_it_shines",
    "warlords_supernatural",
    "walls3_legendary_assassin",
    "walls3_legendary_cow",
    "uhc_extra_powerful",
    "walls3_legendary_herobrine",
    "walls3_legendary_pirate",
    "walls3_legendary_creeper",
    "blitz_brutal_warrior",
    "walls3_remote_detonation",
    "blitz_phoenix_master",
    "speeduhc_my_way",
    "speeduhc_brave_new_world",
    "speeduhc_hot_hog",
    "speeduhc_diamonds",
    "speeduhc_tears_of_loneliness",
    "uhc_obliterate",
    "speeduhc_yeehaw",
    "blitz_first_ranger",
    "uhc_deaths_scythe",
    "walls3_terminated_script",
    "walls3_trust_me_im_a_doctor",
    "uhc_ultimately_wealthy",
    "uhc_exodus",
    "uhc_tablets_of_destiny",
    "walls3_recycling",
    "walls3_tiger_shark",
    "skyblock_combined_efforts",
    "skyblock_lost_soul",
    "skyblock_quest_complete",
    "skyblock_soul_hunter",
    "skyblock_production_expanded",
    "skyblock_happy_new_year",
    "skyblock_your_adventure_begins",
    "skyblock_explorer",
    "skyblock_into_the_deep",
    "skyblock_master_enchanter",
    "skyblock_welcome_to_my_factory",
    "skyblock_promised_fulfilled",
    "skyblock_a_challenging_climb",
    "skyblock_higher_than_a_rabbit",
    "skyblock_hsssss",
    "skyblock_king_of_the_sea",
    "skyblock_death_from_above",
    "skyblock_time_to_start_fishing",
    "skyblock_i_knew_it",
    "skyblock_time_to_go_on_vacation",
    "skyblock_more_space",
    "skyblock_no_enchants_needed",
    "skyblock_overkill",
    "skyblock_brain_power",
    "skyblock_sirius_business",
    "skyblock_flamin_hot",
    "skyblock_precious_minerals",
    "skyblock_the_flint_bros",
    "skyblock_a_good_spider_is_a_dead_spider",
    "skyblock_gottagofast",
    "skyblock_three_birds_one_arrow",
    "skyblock_second_chance",
    "skyblock_supreme_farmer",
    "skyblock_spiky",
    "skyblock_i_am_groot",
    "skyblock_bigger_storage_is_seeded",
    "skyblock_mass_production",
    "skyblock_arcadia",
    "skyblock_super_fuel",
    "skyblock_accessories_galore",
    "skyblock_cute_little_cube",
    "skyblock_true_alchemist",
    "skyblock_it_never_ends",
    "skyblock_the_one_bottle",
    "skyblock_worth_it",
    "skyblock_deep_storage",
    "skyblock_expensive_brew",
    "skyblock_higher_enchants",
    "skyblock_animal_fishing",
    "skyblock_water_sword",
    "skyblock_agile",
    "skyblock_treasure_fishing",
    "skyblock_night_eyes",
    "skyblock_big_game_fisher",
    "skyblock_legendary_rod",
    "skyblock_your_big_break",
    "skyblock_king_of_the_chicks",
    "skyblock_saddle_up",
    "skyblock_advanced_transportation",
    "skyblock_this_is_fair",
    "skyblock_sea_monster",
    "speeduhc_master_of_masters",
    "walls3_sneak_attack",
    "walls3_multi_kill",
    "skyblock_heart_of_the_end",
    "skyblock_safety_first",
    "skyblock_end_race",
    "skyblock_oh_shiny",
    "skyblock_dragon_slayer",
    "skyblock_speed_of_light",
    "skyblock_watch_me_shine",
    "skyblock_explosive_ending",
    "skyblock_shrimp",
    "uhc_ghost_rider",
    "skyblock_baited",
    "tntgames_potion_shower",
    "tntgames_no_you",
    "tntgames_timer",
    "tntgames_pro_surfer",
    "tntgames_freeze",
    "tntgames_flying_madman",
    "tntgames_magnetic_boots",
    "tntgames_combo",
    "tntgames_sniper",
    "tntgames_healer",
    "tntgames_mega_tank",
    "tntgames_win_streak",
    "tntgames_time_wizards",
    "tntgames_patience",
    "tntgames_lucky",
    "tntgames_extrme_speed",
    "walls3_magnate",
    "walls3_yeehaw",
    "walls3_cake_hunter_2",
    "truecombat_monsterkill",
    "walls3_wolf_smash",
    "skyblock_i_am_superior",
    "halloween2017_tbr_clock_tower_trip",
    "halloween2017_tbr_pumpkin_jump",
    "halloween2017_tbr_seaside_drive",
    "halloween2017_tbr_clock_tower_trip_fast",
    "halloween2017_tbr_pumpkin_jump_fast",
    "halloween2017_tbr_seaside_drive_fast",
    "halloween2017_see_through",
    "halloween2017_pumpkins_will_rise",
    "halloween2017_devils_ride",
    "halloween2017_be_free",
    "halloween2017_haunted_maps",
    "halloween2017_tis_the_season",
    "halloween2017_that_time_of_year",
    "halloween2017_killer_loot",
    "halloween2017_five_baskets",
    "halloween2017_all_baskets",
    "halloween2017_fear_the_pumpkinator",
    "halloween2017_spooky_looks",
    "skyblock_dullahan",
    "skyblock_sweet_tooth",
    "skyblock_bat_pinata",
    "general_hot_potato",
    "uhc_wrong_mode",
    "skyblock_friar_lawrence",
    "skyblock_empty_flower_pot",
    "quake_rip",
    "quake_platinum_plated",
    "christmas2017_hunt_begins_2019",
    "christmas2017_spreading_love",
    "christmas2017_to_war",
    "christmas2017_groopo_returns",
    "christmas2017_friendly_fire",
    "skyblock_fortunate",
    "christmas2017_ice_breaker",
    "christmas2017_ice_spreader",
    "christmas2017_explosive_candy",
    "christmas2017_real_santa_2019",
    "christmas2017_rush",
    "christmas2017_secretest_santa",
    "christmas2017_todays_the_day",
    "christmas2017_new_years_celebrations",
    "uhc_feared_hunters",
    "uhc_nothing_can_stop_us",
    "arena_disco_star",
    "walls3_nights_rest",
    "skyblock_caretaker",
    "skyblock_the_real_zoo_shady",
    "skyblock_stubborn_giver",
    "uhc_bloodthirsty",
    "skyblock_friend_for_life",
    "easter_whats_this",
    "easter_what_have_we_done",
    "easter_environment_protection",
    "easter_inner_rabbit",
    "easter_egg_betrayer",
    "easter_egg_assault",
    "easter_first_egg_2020",
    "easter_egg_layer",
    "easter_close_enough",
    "easter_faster_than_wind",
    "easter_all_eggs_2020",
    "pit_max_out_el_gato",
    "pit_do_a_trade",
    "pit_complete_contract_fast",
    "pit_place_obsidian",
    "pit_use_golden_heads",
    "pit_mine_obsidian",
    "pit_collect_from_care_package",
    "pit_full_storage",
    "pit_bid_auction",
    "pit_pentakill",
    "pit_kill_with_strength",
    "pit_claim_bounty",
    "pit_time_on_kotl",
    "pit_get_endless_quiver_arrows",
    "pit_fall_in_void",
    "pit_kill_two_beasts",
    "pit_top_three_in_event",
    "pit_small_streak",
    "pit_win_auction",
    "pit_punch_sword",
    "pit_have_cobblestone",
    "pit_collect_trickle_down",
    "pit_kill_high_bounty",
    "pit_get_lucky_diamond",
    "pit_high_killstreak",
    "pit_squads_many_points",
    "pit_stay_on_koth",
    "pit_reach_level_100",
    "pit_many_clicks_dragon_egg",
    "pit_win_raffle",
    "pit_deliver_many_pizzas",
    "pit_earn_mystic_item",
    "pit_spire_last_floor",
    "pit_purchase_scam_artist",
    "pit_fast_quick_maths",
    "pit_eat_lots_of_cake",
    "pit_get_high_bounty",
    "pit_color_fancy_hat",
    "pit_high_tier_angel",
    "pit_pickup_ingots",
    "pit_bounties_claimed_with_bh",
    "pit_complete_night_quest",
    "pit_use_self_checkout",
    "pit_enchant_tier_three",
    "pit_bake_cake",
    "pit_complete_king_quest",
    "pit_max_out_passives",
    "pit_xp_from_koth",
    "pit_enchant_rare",
    "pit_high_tier_demon",
    "pit_many_kills_as_beast",
    "pit_robbery_cap",
    "skyblock_gotta_go_fast",
    "skyblock_i_believe_i_can_fly",
    "skyblock_rainbow",
    "skyblock_businessman",
    "skyblock_lifelong_contract",
    "skyblock_to_space_we_go",
    "skyblock_storage_forever",
    "skyblock_seriously",
    "skyblock_every_little_bit_helps",
    "skyblock_the_prodigy",
    "skyblock_absorb_it_all",
    "skyblock_zookeeper",
    "summer_punch_out",
    "summer_home_run",
    "summer_grillmaster",
    "summer_bring_the_storm",
    "summer_lightning_rod",
    "summer_pool_party",
    "summer_shockwave",
    "summer_win_pink_sheep",
    "summer_australian_winter",
    "summer_expert_diver",
    "skyblock_happy_holidays",
    "skyblock_frozen_monster",
    "summer_collectors_edition",
    "skyblock_glass_cannon",
    "skyblock_caught_the_grinch",
    "pit_reach_prestige_20",
    "pit_have_a_lot_of_gold",
    "pit_unlock_fast_pass",
    "pit_kills_with_rambo",
    "pit_earn_aqua_pants",
    "skywars_ashes_to_ashes",
    "skywars_killstolen",
    "skywars_teamwork_makes_the_dream_work",
    "skywars_going_ham",
    "pit_consume_everything",
    "skyblock_im_fast_as_heck_boy",
    "skyblock_fully_evolved",
    "skyblock_king_of_the_pets",
    "skyblock_do_you_even_voodoo",
    "skyblock_infinite_darkness",
    "skyblock_knowledge_is_power",
    "skyblock_though_choice",
    "skyblock_jerry",
    "skyblock_speedrunner",
    "skyblock_wonderful_treasures",
    "skyblock_sacrifices_must_be_made",
    "skyblock_the_flash",
    "skyblock_smell_like_roses",
    "skyblock_next_level",
    "skyblock_dungeon_explorer",
    "skyblock_flawless",
    "skyblock_indiana_bones",
    "skyblock_rebirth",
    "skyblock_rough_deal",
    "skyblock_defeating_death",
    "skywars_kit_conoisseur",
    "skyblock_united_in_blood",
    "skyblock_existential_revelations",
    "skyblock_s_plus_squad",
    "skyblock_upgrades_people_upgrades",
    "skyblock_mystical",
    "copsandcrims_armed_and_dangerous",
    "copsandcrims_raise_your_voice",
    "copsandcrims_friendly_fire",
    "copsandcrims_blasted_to_the_moon",
    "copsandcrims_golden_deagle",
    "copsandcrims_special_looks",
    "copsandcrims_jack_of_all_trades",
    "copsandcrims_half_the_battle",
    "copsandcrims_mp5_streak",
    "copsandcrims_ace",
    "copsandcrims_wrecking_machine",
    "skyblock_librarian",
    "copsandcrims_p90_streak",
    "arcade_ctw_i_can_be_anything",
    "arcade_ctw_comeback",
    "arcade_ctw_hey_there",
    "arcade_ctw_ninja",
    "arcade_ctw_no_need",
    "arcade_ctw_safety_is_an_illusion",
    "arcade_ctw_first",
    "arcade_ctw_mvp",
    "arcade_ctw_magician",
    "arcade_ctw_fashionably_late",
    "arcade_ctw_right_place_right_time",
    "pit_max_out_renown",
    "halloween2017_master_bobber",
    "halloween2017_tricked",
    "halloween2017_full_bat_mode",
    "halloween2017_five_baskets_2020",
    "halloween2017_loose_floorboard",
    "halloween2017_spooky_victory",
    "halloween2017_burning_touch",
    "halloween2017_smoking_veil",
    "halloween2017_all_baskets_2020",
    "halloween2017_sugar_rush",
    "halloween2017_trick_or_treat_time",
    "christmas2017_hunt_begins_2020",
    "christmas2017_real_santa_2020",
    "pit_heal_with_vampire",
    "pit_eat_rage_potatoes",
    "pit_top_three_rage_pit",
    "general_first_join",
    "skyblock_royal_resident_dialogue",
    "walls3_biological_restoration",
    "walls3_heavy_eater",
    "skyblock_true_adventurer",
    "easter_first_egg_2021",
    "easter_you_didnt_see_that_coming",
    "easter_spring_fishing",
    "easter_spring_maiden",
    "easter_egg_master",
    "easter_all_eggs_2021",
    "easter_what_is_this",
    "easter_spring_hero",
    "easter_happy_easter_2021",
    "general_treasure_hunt_2021",
    "summer_cool_off",
    "summer_kind_refreshment",
    "summer_out_fishing",
    "summer_stay_hydrated",
    "summer_ocean_in_a_bucket",
    "summer_this_isnt_the_lobby",
    "summer_sun_denial",
    "summer_ice_cold",
    "summer_sunburnt",
    "summer_beat_the_heat",
    "summer_rule_the_heat",
    "summer_drought",
    "summer_oasis_jake",
    "summer_seaside_shootout",
    "summer_wrong_season",
    "summer_bbq_in_the_sky",
    "skyblock_peak_of_the_mountain",
    "skyblock_resourceful",
    "skyblock_royal_meeting",
    "skyblock_nightmare",
    "skyblock_next_generation",
    "skyblock_ghost_buster",
    "skyblock_hidden_secrets",
    "skyblock_beaconator_two",
    "skyblock_fallen_star_cult",
    "skyblock_goblin_slayer",
    "uhc_champion_rank",
    "skyblock_a_good_review",
    "skyblock_eternal_flame_ring",
    "skyblock_dragons_egg",
    "skyblock_helpful_hand",
    "murdermystery_trapper_territory",
    "murdermystery_xom_b",
    "murdermystery_sixth_sense",
    "murdermystery_tricked",
    "murdermystery_disinfectant",
    "murdermystery_double_duty",
    "uhc_ace_kit",
    "uhc_production_ender",
    "uhc_master_magician",
    "uhc_treasure_of_el_dorado",
    "uhc_dragon_warrior",
    "uhc_one_pound_slap",
    "uhc_modifier_master",
    "uhc_uhc_expert",
    "uhc_crafting_maniac",
    "uhc_accidental_summoning",
    "halloween2017_five_baskets_2021",
    "halloween2017_all_baskets_2021",
    "halloween2017_master_alchemist",
    "halloween2017_sugar_rush_2",
    "skyblock_magical_place",
    "skyblock_i_call_that_mercy",
    "skyblock_didnt_mean_to",
    "skyblock_should_have_stayed_cool",
    "skyblock_smells_better",
    "skyblock_how_to_train_your_dragon",
    "skyblock_prepare_for_trouble",
    "skyblock_lapidarist",
    "arcade_football_potm",
    "arcade_galaxy_wars_lethally_blind",
    "arcade_galaxy_wars_perfect_deflect",
    "arcade_galaxy_wars_aimed",
    "arcade_hypixel_says_pig_rider",
    "arcade_hypixel_says_tnt_dodger",
    "arcade_hypixel_says_bad_health_choices",
    "arcade_hypixel_says_pve_expert",
    "arcade_blocking_dead_rescue",
    "arcade_party_sheep_rider",
    "arcade_hypixel_says_movement",
    "arcade_dw_void",
    "arcade_ender_spleef_no_powerhouse",
    "arcade_party_fast_hands",
    "arcade_galaxy_wars_target_practice",
    "arcade_bounty_hunters_sniper",
    "arcade_galaxy_wars_now_i_am_the_master",
    "arcade_galaxy_wars_never_felt_better",
    "arcade_hide_and_seek_speedrunner",
    "arcade_party_in_sync",
    "arcade_party_parkour",
    "arcade_dw_quick_win",
    "arcade_throw_out_regular_guy",
    "arcade_party_picasso",
    "arcade_hide_and_seek_close_call",
    "arcade_party_perfection",
    "arcade_party_survivor",
    "duels_master_builders",
    "duels_jack_of_all_trades",
    "duels_speedster",
    "duels_change_icon",
    "duels_boxing_combo",
    "duels_silent_thief",
    "duels_arena_master",
    "duels_flawless",
    "christmas2017_hunt_begins_2021",
    "christmas2017_real_santa_2021",
    "christmas2017_ice_king",
    "christmas2017_snow_turret",
    "christmas2017_snowball_fight",
    "christmas2017_snowball_sniper",
    "christmas2017_snow_problem",
    "christmas2017_present_priorities",
    "blitz_jack_of_all_trades",
    "blitz_counterplay",
    "blitz_rambo_indeed",
    "blitz_frame_of_mind",
    "blitz_theres_levels_to_this",
    "blitz_are_you_not_entertained",
    "blitz_summoner",
    "blitz_party_animal",
    "blitz_nuke_incoming",
    "skywars_the_angels_journey",
    "copsandcrims_the_best_around",
    "copsandcrims_so_much_better",
    "copsandcrims_swordfighter",
    "copsandcrims_legends_never_die",
    "general_grapple_pro",
    "general_tips_and_tricks",
    "general_lobby_explorer",
    "general_crash_landed",
    "general_fishing_hobbyist",
    "general_keep_quiet",
    "general_code_breaker",
    "general_labyrinthine_collector",
    "general_hypixel_historian",
    "general_doing_my_part",
    "general_deep_sea_expert",
    "general_old_farmers_almanac",
    "easter_first_egg_2022",
    "easter_all_eggs_2022",
    "easter_spring_water",
    "easter_hop_to_it",
    "easter_saving_the_planet",
    "easter_springtime_match_ups",
    "easter_pep_in_your_step",
    "general_treasure_hunt_2022",
    "easter_happy_easter_2022",
    "easter_midspring_nights_dream",
    "skyblock_dojo_master",
    "skyblock_declaring_allegiance",
    "skyblock_kuudra_conundrum",
    "skyblock_scam",
    "skyblock_ring_ring_whos_this",
    "skyblock_suited_up",
    "skyblock_the_itsy_bitsy_spider",
    "skyblock_blaze_wrangler",
    "skyblock_amalgamation",
    "skyblock_wasted_potential",
    "skyblock_this_is_the_way",
    "skyblock_meal_fit_for_a_king",
    "skyblock_shining_scales",
    "skyblock_vanquished",
    "skyblock_i_own_this_place",
    "skyblock_dojo_grand_master",
    "skyblock_geronimo",

}

export interface HYPIXEL_ACHIEVEMENTS {
    skywars_kills_team: number,
    skywars_wins_team: number,
    skywars_kills_solo: number,
    skywars_wins_solo: number,
    skywars_kits_solo: number,
    skywars_kits_teams: number,
    skywars_cages: number,
    general_wins: number,
    truecombat_kit_hoarder_team: number,
    truecombat_kit_hoarder_solo: number,
    truecombat_team_killer: number,
    truecombat_solo_killer: number,
    blitz_coins: number,
    blitz_kills: number,
    general_coins: number,
    truecombat_team_winner: number,
    supersmash_smash_champion: number,
    supersmash_smash_winner: number,
    supersmash_hero_slayer: number,
    uhc_moving_up: number,
    uhc_hunter: number,
    uhc_champion: number,
    uhc_bounty: number,
    supersmash_handyman: number,
    blitz_wins: number,
    arena_gladiator: number,
    arena_bossed: number,
    arena_climb_the_ranks: number,
    arena_gotta_wear_em_all: number,
    quake_kills: number,
    quake_wins: number,
    copsandcrims_bomb_specialist: number,
    tntgames_bow_spleef_wins: number,
    skywars_kills_mega: number,
    skywars_kits_mega: number,
    skywars_wins_mega: number,
    general_challenger: number,
    general_quest_master: number,
    speeduhc_hunter: number,
    speeduhc_uhc_master: number,
    speeduhc_collector: number,
    speeduhc_salty: number,
    paintball_wins: number,
    paintball_kills: number,
    paintball_coins: number,
    copsandcrims_cac_banker: number,
    warlords_warrior_level: number,
    warlords_paladin_level: number,
    warlords_shaman_level: number,
    warlords_mage_level: number,
    walls3_coins: number,
    walls3_guardian: number,
    copsandcrims_serial_killer: number,
    copsandcrims_hero_terrorist: number,
    tntgames_tnt_run_wins: number,
    skyclash_packs_opened: number,
    skyclash_cards_unlocked: number,
    skyclash_kills: number,
    skyclash_wins: number,
    vampirez_coins: number,
    vampirez_kill_vampires: number,
    vampirez_survivor_wins: number,
    vampirez_kill_survivors: number,
    walls3_wins: number,
    walls3_rusher: number,
    warlords_assist: number,
    warlords_coins: number,
    warlords_kills: number,
    warlords_ctf_wins: number,
    warlords_repair_weapons: number,
    warlords_dom_wins: number,
    truecombat_solo_winner: number,
    warlords_tdm_wins: number,
    walls3_kills: number,
    arcade_arcade_banker: number,
    arcade_arcade_winner: number,
    arcade_miniwalls_winner: number,
    arcade_team_work: number,
    arcade_football_pro: number,
    arcade_farmhunt_dominator: number,
    arcade_bounty_hunter: number,
    tntgames_wizards_wins: number,
    quake_coins: number,
    skyclash_treasure_hunter: number,
    skyclash_mob_beheading: number,
    quake_headshots: number,
    quake_weapon_arsenal: number,
    gingerbread_banker: number,
    gingerbread_racer: number,
    vampirez_zombie_killer: number,
    quake_killing_sprees: number,
    tntgames_tnt_wizards_kills: number,
    tntgames_tnt_tag_wins: number,
    tntgames_pvp_run_wins: number,
    tntgames_pvp_run_killer: number,
    tntgames_tnt_triathlon: number,
    tntgames_tnt_banker: number,
    tntgames_tnt_wizards_caps: number,
    walls_coins: number,
    gingerbread_winner: number,
    blitz_war_veteran: number,
    blitz_wins_teams: number,
    blitz_looter: number,
    blitz_treasure_seeker: number,
    bedwars_wins: number,
    bedwars_beds: number,
    bedwars_level: number,
    bedwars_loot_box: number,
    walls_kills: number,
    quake_godlikes: number,
    truecombat_king: number,
    truecombat_feels_lucky: number,
    murdermystery_wins_as_survivor: number,
    murdermystery_kills_as_murderer: number,
    murdermystery_wins_as_murderer: number,
    halloween2017_pumpkin_smasher: number,
    halloween2017_pumpkinator: number,
    christmas2017_advent: number,
    christmas2017_santa_says_rounds: number,
    christmas2017_no_christmas: number,
    arcade_zombie_killer: number,
    walls_wins: number,
    buildbattle_build_battle_points: number,
    buildbattle_guess_the_build_guesses: number,
    buildbattle_build_battle_score: number,
    buildbattle_guess_the_build_winner: number,
    buildbattle_build_battle_voter: number,
    duels_duels_winner: number,
    duels_duels_win_streak: number,
    duels_duels_trophies: number,
    walls3_jack_of_all_trades: number,
    walls3_cake_hunter_tiered: number,
    blitz_rng_master: number,
    blitz_master_of_kits: number,
    blitz_kit_expert: number,
    skywars_wins_lab: number,
    bridge_goals: number,
    bridge_one_v_one_wins: number,
    bridge_unique_map_wins: number,
    bridge_wins: number,
    bridge_win_streak: number,
    bridge_four_v_four_wins: number,
    arcade_hide_and_seek_hider_kills: number,
    arcade_zombies_round_progression: number,
    bridge_four_teams_wins: number,
    bedwars_collectors_edition: number,
    bedwars_bedwars_killer: number,
    copsandcrims_headshot_kills: number,
    copsandcrims_grenade_kills: number,
    murdermystery_hoarder: number,
    tntgames_clinic: number,
    duels_duels_division: number,
    duels_duels_traveller: number,
    warlords_ctf_objective: number,
    warlords_dom_objective: number,
    walls3_moctezuma: number,
    gingerbread_mystery: number,
    duels_bridge_win_streak: number,
    duels_bridge_wins: number,
    duels_bridge_doubles_wins: number,
    duels_unique_map_wins: number,
    duels_goals: number,
    duels_bridge_teams_wins: number,
    duels_bridge_duels_wins: number,
    duels_bridge_four_teams_wins: number,
    paintball_kill_streaks: number,
    paintball_hat_collector: number,
    paintball_invincible: number,
    arena_magical_box: number,
    arena_powerup: number,
    christmas2017_advent_2018: number,
    walls_diamond_miner: number,
    skywars_heads: number,
    uhc_consumer: number,
    blitz_kit_collector: number,
    blitz_fighting_expert: number,
    blitz_mob_master: number,
    blitz_kit_experience_collector: number,
    blitz_chaos_winner: number,
    blitz_ranged_combat: number,
    easter_throw_eggs: number,
    arcade_zombies_nice_shot: number,
    arcade_zombies_high_round: number,
    speeduhc_promotion: number,
    uhc_ultimatum: number,
    skyblock_minion_lover: number,
    skyblock_excavator: number,
    skyblock_harvester: number,
    skyblock_treasury: number,
    skyblock_combat: number,
    skyblock_gatherer: number,
    skyblock_angler: number,
    skyblock_concoctor: number,
    skyblock_augmentation: number,
    tntgames_block_runner: number,
    christmas2017_advent_2019: number,
    christmas2017_present_collector: number,
    christmas2017_secret_santa: number,
    skyblock_unique_gifts: number,
    easter_egg_finder: number,
    easter_master_tracker: number,
    pit_gold: number,
    pit_kills: number,
    pit_contracts: number,
    pit_events: number,
    pit_prestiges: number,
    pit_renown: number,
    pit_mysticism: number,
    skyblock_domesticator: number,
    skyblock_slayer: number,
    summer_shopaholic: number,
    summer_treasure_hoarder: number,
    summer_treasure_master: number,
    summer_gone_fishing: number,
    skywars_new_day_new_challenge: number,
    skywars_you_re_a_star: number,
    skywars_opal_obsession: number,
    skyblock_treasure_hunter: number,
    skyblock_dungeoneer: number,
    copsandcrims_practice_makes_perfect: number,
    arcade_ctw_oh_sheep: number,
    arcade_ctw_slayer: number,
    halloween2017_get_them_apples: number,
    halloween2017_candy_hoarder: number,
    halloween2017_brave_the_dark: number,
    christmas2017_advent_2020: number,
    christmas2017_best_presents: number,
    skyblock_hard_working_miner: number,
    skyblock_goblin_killer: number,
    murdermystery_hitman: number,
    murdermystery_brainiac: number,
    murdermystery_survival_skills: number,
    murdermystery_countermeasures: number,
    bedwars_bedwars_challenger: number,
    skyblock_divans_treasures: number,
    skyblock_crystal_nucleus: number,
    arcade_dw_slayer: number,
    arcade_galaxy_wars_kills: number,
    arcade_throw_out_kills: number,
    arcade_party_super_star: number,
    arcade_hitw_practice_makes_perfect: number,
    arcade_dw_dragonborn: number,
    arcade_ender_spleef_powerups: number,
    arcade_ender_spleef_block_stealer: number,
    arcade_hide_and_seek_master_hider: number,
    duels_duels_mastery: number,
    duels_arena_mastery: number,
    christmas2017_advent_2021: number,
    blitz_disrespect: number,
    copsandcrims_any_gun_any_time: number,
    general_master_lure: number,
    general_luckiest_of_the_sea: number,
    general_trashiest_diver: number,
}